Added 2d gradient descent prototype
waynebhayes/CellUniverse pull request #151
Opened 2023-11-10 20:00 UTC by YS0meone

2D gradient descent optimizer running on the first 10 frames of the canonical example. Potential problem and solutions are included in the README

2023-11-11 02:08 UTC, waynebhayes commented on gradient_descent_prototype/Pipfile.lock
Is this file really needed?

2023-11-11 02:11 UTC, waynebhayes requested changes
Looks cool, but I think there are a couple files that may not be necessary. Also, can you provide a regression test that shows the 2D GD code working?

2023-11-11 02:11 UTC, waynebhayes commented on gradient_descent_prototype/video0/log.txt
Is this file needed? eg is it part of a regression test?

2023-11-13 22:50 UTC, YS0meone commented on gradient_descent_prototype/Pipfile.lock
This file is actually needed since the new environment seems to have some numpy version conflict with the code here.

2023-11-13 22:51 UTC, YS0meone commented on gradient_descent_prototype/video0/log.txt
I will remove this and add a regression test.

2023-11-14 00:08 UTC, waynebhayes approved these changes

2023-11-14 00:08 UTC, merged